spring:
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          zkNodes: 'localhost:2181'
          brokers: 'localhost:9092'

server:
  port: 8080

zuul:
  routes:
    merchant-service:
      path: "/merchants**"
      strip-prefix: false

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]