spring:
  cloud:
    bus:
      enable: true
    config:
      server:
        git:
          uri: 'https://github.com/minarashidi/config-repository'
          clone-on-start: true
          search-paths: 'config/{application}'

    stream:
      kafka:
        binder:
          zkNodes: 'localhost:2181'
          brokers: 'localhost:9092'

# Server properties
server:
  port: 8888
